spring:
  profiles:
    active: dev 
---
spring: 
  kafka:
    bootstrap-servers:            # 定义主机列表
    - kafka-single:9095
    template:
      default-topic: mldn-microboot   # 定义主题名称
    producer:                     # 定义生产者配置
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:                   # 定义消费者配置
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: group-1             # 数据分组
    properties:
      sasl.mechanism: PLAIN           # 安全机制
      security.protocol: SASL_PLAINTEXT   # 安全协议
  profiles: dev 
  messages:
    basename: i18n/Message
  thymeleaf:
    servlet:
      content-type: text/html 
    cache: false 
    mode: LEGACYHTML5
server: 
  port: 80
