spring:
  profiles:
    active: dev 
---
spring:
  rabbitmq:
    host: 192.168.188.148
    username: mldn
    password: java
    virtual-host: /mldnjava
  profiles: dev 
  messages:
    basename: i18n/Message
  thymeleaf:
    servlet:
      content-type: text/html 
    cache: false 
    mode: LEGACYHTML5
server: 
  port: 80
